FROM alpine:latest

LABEL maintainer="AndresSantos<AndresSantostkd@gmail.com>"

RUN apk update && \
    apk upgrade && \
    apk add --no-cache nginx

RUN mkdir -p /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
